#!/usr/bin/env bash
#
# LEXIAN — Wartungszugang einrichten
#
# Generated by Radix for exactly ONE instance. Every value in the CONFIG block
# is baked in at download time, which is why this script takes no options: the
# instance, the maintenance user, the reserved tunnel ports and the expected
# key fingerprint are decisions Radix already made. Handing it to a different
# machine fails on the fingerprint check rather than half-configuring the
# wrong box.
#
# ---------------------------------------------------------------------------
# Why the shape of this script is what it is
#
# The customer machine can only reach Radix outbound (see
# RADIX_INSTANCE_CONNECTIVITY.md). It opens ONE ssh connection carrying two
# remote forwards:
#
#   -R <ssh_target_port>     -> 127.0.0.1:22        so Radix can run setup-radix
#   -R <handoff_target_port> -> <unix socket>       the credential handoff
#
# Radix then CONNECTS IN to the handoff port and reads the credentials. That
# direction is deliberate: no inbound endpoint has to be published for
# enrollment, and no shared secret has to travel with this script.
# Authentication is the port binding itself — the access host's sshd confines
# this instance's key (permitlisten) to exactly the ports reserved for it, so
# whoever answers on that port provably holds this instance's key.
#
# The handoff endpoint is a UNIX SOCKET, not a TCP port on localhost. A
# localhost TCP listener would be readable by every local process for the
# duration of the run, which would hand any unprivileged local user a
# sudo-capable password. The socket lives in a 0700 root-owned directory with
# mode 0600, so only root can read it.
#
# `ssh -R <port>:<unix socket>` works even though the access host sets
# `AllowStreamLocalForwarding no`: that directive governs SERVER-side unix
# sockets, while here the server only opens a plain TCP listener and the
# socket is entirely client-side. Verified against the real access image —
# the equivalent server-side form (`-R /remote.sock:...`) is refused, this
# form is not.
#
# Handoff protocol (newline-delimited JSON, one object per line):
#
#   1. Radix connects to accesshost:<handoff_target_port>.
#   2. This script sends exactly one line:
#        {"v": 1, "os_user": ..., "password": ...,
#         "sudo_ok": true|false, "password_auth": true|false,
#         "status_file": "/home/lexian/.lexian-enroll.status",
#         "host_keys": [...], "hostname": ..., "os": ...}
#   3. Radix streams progress lines back, each:
#        {"state": "<state>", "message": "<text for the customer>"}
#      Terminal states are "done" and "failed"; anything else is informational.
#   4. The script prints every message and holds the tunnel until a terminal
#      state arrives (setup-radix needs the :22 forward the whole time), then
#      exits 0 on "done" and 1 on "failed".
#
# Radix may connect more than once (probe, retry); each connection is served
# the same payload.
#
# ---------------------------------------------------------------------------
# Design rules for this script
#
#   * No options, no questions. Everything is baked in or detected. There is
#     no `read` anywhere, so it also survives being piped into bash and needs
#     no terminal.
#   * The maintenance user's password is ALWAYS freshly generated here and
#     handed to Radix. We never ask a human to type or remember it, which
#     removes the entire class of "wrong password" failures — and it means the
#     script cannot be run wrongly, only successfully or not at all.
#   * Re-running is always safe and is the documented remedy for any failure:
#     a second run generates a new password and hands it over again.
#   * Missing preconditions are fixed, not reported, wherever the script can
#     legitimately fix them (python3, the maintenance user, its shell, its home
#     directory, its sudo group membership). Only genuinely external problems
#     (no network, wrong machine, no package sources) end the run.
#
# ---------------------------------------------------------------------------
# Rendering contract
#
# This file is NOT a Django template. Radix produces a customer-ready script by
# replacing each doubled-at marker in the CONFIG block with a literal value —
# nothing else. That choice is deliberate: every marker sits inside single
# quotes, so the file in
# the repository is itself valid bash and can be syntax-checked, shellchecked
# and executed by the test suite without a rendering step or a Django import.
#
# The full token list, the value each one expects and the test suite live in
# enroll/README.md. A script that still contains an unsubstituted token refuses
# to run (see the check right after the CONFIG block) rather than failing
# somewhere in the middle with a confusing error.
#
# Conventions: comments and identifiers English (repo convention), everything
# printed to the customer German.

set -euo pipefail

# --- CONFIG (rendered by Radix) --------------------------------------------

# Deployment-global only. Every customer of this Radix receives byte-identical
# bytes; the per-instance values (access host, reserved port) arrive as flags.
#
# RADIX_HOST/RADIX_PORT are the DEFAULT access host — a Radix can have several,
# and which one an instance belongs to is per-instance, so --host overrides them.
RADIX_HOST='maintenance.lexian.ch'
RADIX_PORT='2222'
TUNNEL_USER='kajxeb-6torcu'
OS_USER='lexian'
SUPPORT_CONTACT='technik@lexian.ch'

# Budget for the whole handoff + setup phase. Generous: setup-radix installs
# packages on a cold machine.
HANDOFF_DEADLINE_S=5400

# --- Rendering check -------------------------------------------------------
# A script handed out with an unsubstituted marker would fail somewhere in the
# middle — e.g. ssh trying to resolve a hostname that is still a marker — and
# the customer would report a confusing error. Refuse up front instead. This
# also means the unrendered file in the repository cannot be run by accident.

for _config_var in RADIX_HOST RADIX_PORT TUNNEL_USER OS_USER \
                   SUPPORT_CONTACT
do
    case "${!_config_var}" in
        *@@*)
            printf 'Dieses Skript ist unvollständig (%s wurde nicht ersetzt).\n' \
                "$_config_var" >&2
            printf 'Bitte das Skript erneut in Radix herunterladen.\n' >&2
            exit 3
            ;;
    esac
done
unset _config_var

# --- No options ------------------------------------------------------------

explain() {
    cat <<EOF
LEXIAN — Wartungszugang einrichten

Aufruf:

    sudo bash install.sh --host <SERVER> --host-key <FINGERPRINT> \\
                         --port <NUMMER>

Beide Angaben stehen im LEXIAN Onboarding-Portal beim Download dieses Skripts.
Keine davon ist geheim: stimmt etwas nicht, verweigert LEXIAN die Verbindung —
es kann nichts Unerwünschtes passieren.

  --port <NUMMER>       der für diese Maschine reservierte Port.
  --host <SERVER>       Zugangspunkt von LEXIAN, Form name oder name:port.
                        Standard: $RADIX_HOST:$RADIX_PORT.
  --host-key <SHA256:…> Fingerprint dieses Servers. Das Skript holt den
                        Schlüssel des Servers und bricht ab, wenn er nicht
                        passt — so kann die Verbindung nicht auf einen
                        fremden Server umgelenkt werden.

Weitere Optionen gibt es nicht — alles andere fragt das Skript ab oder erkennt
es selbst. Es führt folgende Schritte aus:

  1. Prüft die Voraussetzungen (root-Rechte, ssh, Erreichbarkeit) und
     installiert python3, falls es fehlt.
  2. Legt das Benutzerkonto "$OS_USER" an, falls es fehlt, und klärt dessen
     Passwort mit Ihnen.
  3. Sucht die SSH-Schlüssel dieser Maschine.
  4. Fasst zusammen, was verändert wird, und fragt einmal nach.
  5. Baut eine ausgehende Verbindung zu LEXIAN auf und übergibt die
     Zugangsdaten. Es werden KEINE eingehenden Ports geöffnet.

Bei einem Abbruch kann das Skript jederzeit erneut ausgeführt werden.
Rückfragen: $SUPPORT_CONTACT
EOF
}

ENROLL_PORT=""
HOST_ARG=""
HOST_KEY_FP=""

while [ $# -gt 0 ]; do
    case "$1" in
        --port)     ENROLL_PORT="${2:-}"; shift 2 || true ;;
        --port=*)   ENROLL_PORT="${1#--port=}"; shift ;;
        --host)     HOST_ARG="${2:-}"; shift 2 || true ;;
        --host=*)   HOST_ARG="${1#--host=}"; shift ;;
        --host-key)   HOST_KEY_FP="${2:-}"; shift 2 || true ;;
        --host-key=*) HOST_KEY_FP="${1#--host-key=}"; shift ;;
        --help|-h|help) explain; exit 0 ;;
        *)
            printf 'Unbekannte Angabe: %s\n\n' "$1" >&2
            explain >&2
            exit 2
            ;;
    esac
done

case "$ENROLL_PORT" in
    "")
        printf 'Es fehlt die Portnummer.\n\n' >&2
        explain >&2
        exit 2
        ;;
    *[!0-9]*)
        printf 'Die Portnummer muss eine Zahl sein (erhalten: %s).\n' "$ENROLL_PORT" >&2
        exit 2
        ;;
esac
if [ "$ENROLL_PORT" -lt 1 ] || [ "$ENROLL_PORT" -gt 65535 ]; then
    printf 'Die Portnummer liegt ausserhalb des gültigen Bereichs: %s\n' "$ENROLL_PORT" >&2
    exit 2
fi

# --host HOST[:PORT] — welcher Zugangspunkt von LEXIAN benutzt wird. Ohne Angabe
# der eingebackene Standard. Der Port ist optional, damit der übliche Fall kurz
# bleibt; angegeben werden muss er nur, wenn dieser Zugangspunkt einen anderen
# benutzt.
if [ -n "$HOST_ARG" ]; then
    case "$HOST_ARG" in
        *:*)
            RADIX_HOST="${HOST_ARG%%:*}"
            RADIX_PORT="${HOST_ARG##*:}"
            ;;
        *)
            RADIX_HOST="$HOST_ARG"
            ;;
    esac
    case "$RADIX_HOST" in
        ""|*[!a-zA-Z0-9.-]*)
            printf 'Ungültiger Hostname: %s\n' "$RADIX_HOST" >&2
            exit 2
            ;;
    esac
    case "$RADIX_PORT" in
        ""|*[!0-9]*)
            printf 'Ungültiger Port in --host: %s\n' "$HOST_ARG" >&2
            exit 2
            ;;
    esac
fi

# Der Fingerprint des Zugangspunkts ist Pflicht, sobald ein Host genannt wird —
# und auch fuer den Standard-Host, denn ohne ihn gaebe es keinen Pin und die
# Uebergabe ginge an jeden, der auf dem Namen antwortet. Ein optionaler Pin ist
# ein Pin, der weggelassen wird.
case "$HOST_KEY_FP" in
    "")
        printf 'Es fehlt der Fingerprint des LEXIAN-Servers (--host-key).\n\n' >&2
        explain >&2
        exit 2
        ;;
    SHA256:*) ;;
    *)
        printf 'Der Fingerprint muss mit "SHA256:" beginnen (erhalten: %s).\n' \
            "$HOST_KEY_FP" >&2
        exit 2
        ;;
esac

# --- Output helpers --------------------------------------------------------

if [ -t 1 ]; then
    C_RESET=$'\033[0m'; C_BOLD=$'\033[1m'
    C_RED=$'\033[31m'; C_YELLOW=$'\033[33m'; C_GREEN=$'\033[32m'
else
    C_RESET=""; C_BOLD=""; C_RED=""; C_YELLOW=""; C_GREEN=""
fi

step()  { printf '\n%s==>%s %s\n' "$C_BOLD" "$C_RESET" "$*"; }
# An empty argument means a blank separator line, not four spaces of trailing
# whitespace — which is what it produced before, visible in any editor or diff.
info()  { if [ -z "$*" ]; then printf '\n'; else printf '    %s\n' "$*"; fi; }
ok()    { printf '    %s✓%s %s\n' "$C_GREEN" "$C_RESET" "$*"; }
warn()  { printf '    %sWarnung:%s %s\n' "$C_YELLOW" "$C_RESET" "$*" >&2; }
fail()  {
    printf '\n%sFehler:%s %s\n' "$C_RED" "$C_RESET" "$*" >&2
    printf '\nDas Skript kann jederzeit erneut ausgeführt werden.\n' >&2
    printf 'Bei Fragen: %s\n' "$SUPPORT_CONTACT" >&2
    exit 1
}

# --- Prompts ---------------------------------------------------------------
# Questions are read from /dev/tty, never from stdin: the script must keep
# working when it is piped into bash (`curl … | bash`), where stdin carries the
# script text itself. If no terminal is attached at all, the run proceeds
# unattended with every default — same outcome, no hanging prompt. The subshell
# around the probe matters: a failing `exec` would otherwise kill the script.

INTERACTIVE=0
if (exec </dev/tty) 2>/dev/null; then INTERACTIVE=1; fi

# $1 question, $2 default. Prints the answer on stdout, the prompt on the tty.
#
# The default is SHOWN in brackets and taken when the answer is empty. The
# tempting alternative — `read -e -i "$default"`, which puts the default on the
# input line for editing — was tried and rejected: the prefill sits in the
# readline buffer, so a customer who simply types their own value gets it
# appended to the suggestion. A generated password plus a typed one produced a
# silent concatenation of both. Enter-to-accept has no such failure mode.
ask_line() {
    local question="$1" default="$2" reply=""
    if [ "$INTERACTIVE" -eq 0 ]; then
        printf '%s' "$default"
        return 0
    fi
    printf '    %s [%s]: ' "$question" "$default" > /dev/tty
    IFS= read -r reply < /dev/tty || reply=""
    [ -n "$reply" ] || reply="$default"
    printf '%s' "$reply"
}

ask_yes_no() {
    # $1 question, $2 default ("j" or "n"). Returns 0 for yes.
    local question="$1" default="${2:-j}" reply="" hint="[J/n]"
    [ "$default" = "j" ] || hint="[j/N]"
    if [ "$INTERACTIVE" -eq 0 ]; then
        [ "$default" = "j" ]
        return $?
    fi
    while :; do
        printf '    %s %s ' "$question" "$hint" > /dev/tty
        IFS= read -r reply < /dev/tty || reply=""
        [ -n "$reply" ] || reply="$default"
        case "$reply" in
            [jJyY]|[jJ][aA]|[yY][eE][sS]) return 0 ;;
            [nN]|[nN][oO]|[nN][eE][iI][nN]) return 1 ;;
            *) printf '    Bitte "j" oder "n" eingeben.\n' > /dev/tty ;;
        esac
    done
}

# Hidden answer, no default: for a password the customer already has. Not
# double-entered on purpose — we verify it against the system instead, which
# catches typos AND a genuinely wrong password.
ask_secret() {
    local question="$1" reply=""
    if [ "$INTERACTIVE" -eq 0 ]; then
        printf ''
        return 0
    fi
    printf '    %s: ' "$question" > /dev/tty
    IFS= read -rs reply < /dev/tty || reply=""
    printf '\n' > /dev/tty
    printf '%s' "$reply"
}

# POSIX-portable account name. Rejecting bad input here beats a cryptic
# useradd error, and the customer gets to try again.
valid_username() {
    case "$1" in
        "") return 1 ;;
        [!a-z_]*) return 1 ;;
        *[!a-z0-9_-]*) return 1 ;;
    esac
    [ "${#1}" -le 32 ]
}

#: Set when a package install happened. It is the one change that cannot wait
#: for the summary — the questions themselves need python3 (generating and
#: verifying the password) — so it is asked for separately and reported here
#: rather than swept under a blanket "nothing was changed".
PYTHON_INSTALLED=0

abort() {
    printf '\nAbgebrochen.\n'
    if [ "$PYTHON_INSTALLED" -eq 1 ]; then
        printf 'Verändert wurde nur eines: python3 wurde installiert.\n'
        printf 'Weder ein Benutzerkonto noch der SSH-Server wurden angefasst.\n'
    else
        printf 'Es wurde nichts verändert.\n'
    fi
    printf 'Das Skript kann jederzeit erneut ausgeführt werden.\n'
    exit 0
}

# --- Single instance lock --------------------------------------------------
# Two concurrent runs would fight over the same reserved ports and hand over
# two different passwords. mkdir is atomic on every filesystem we care about;
# a lock left behind by a killed run is taken over once its pid is gone.

# One enrollment per machine at a time. The script no longer knows an instance
# name, and a machine only ever enrolls as one instance anyway.
LOCKDIR="/tmp/lexian-enroll.lock"
LOCK_HELD=0

# Is the pid in the lock file really another run of this script?
#
# A live pid alone is not enough: pids get recycled, and then a lock left behind
# by a killed run looks busy forever. Observed first-hand — a container reused
# the pid, and every later run refused to start with "es läuft bereits eine
# Einrichtung". So confirm the process really is this script before believing it.
# If /proc cannot be read we stay conservative and treat the lock as live: never
# stomp a run that might be real.
lock_owner_alive() {
    local pid="$1" cmdline=""
    case "$pid" in
        ""|*[!0-9]*) return 1 ;;
    esac
    kill -0 "$pid" 2>/dev/null || return 1
    cmdline="$(tr '\0' ' ' < "/proc/$pid/cmdline" 2>/dev/null || true)"
    case "$cmdline" in
        "")            return 0 ;;
        *"${0##*/}"*)  return 0 ;;
        *)             return 1 ;;
    esac
}

acquire_lock() {
    if mkdir "$LOCKDIR" 2>/dev/null; then
        LOCK_HELD=1
        printf '%s' "$$" > "$LOCKDIR/pid"
        return 0
    fi
    local other=""
    other="$(cat "$LOCKDIR/pid" 2>/dev/null || true)"
    if lock_owner_alive "$other"; then
        fail "Es läuft bereits eine Einrichtung (Prozess $other).
    Bitte diese zuerst beenden oder abwarten."
    fi
    # Stale lock: previous run died without cleaning up.
    rm -rf "$LOCKDIR"
    mkdir "$LOCKDIR" 2>/dev/null || fail "Sperrverzeichnis $LOCKDIR nicht anlegbar."
    LOCK_HELD=1
    printf '%s' "$$" > "$LOCKDIR/pid"
}

# --- Workspace / cleanup ---------------------------------------------------

WORKDIR=""
HANDOFF_PID=""
CONTROL_SOCKET=""
CONTROL_UP=0

cleanup() {
    local rc=$?
    if [ -n "$HANDOFF_PID" ] && kill -0 "$HANDOFF_PID" 2>/dev/null; then
        kill "$HANDOFF_PID" 2>/dev/null || true
    fi
    if [ "$CONTROL_UP" -eq 1 ]; then
        ssh -S "$CONTROL_SOCKET" -O exit "$RADIX_HOST" >/dev/null 2>&1 || true
    fi
    [ -n "$WORKDIR" ] && rm -rf "$WORKDIR"
    [ "$LOCK_HELD" -eq 1 ] && rm -rf "$LOCKDIR"
    return $rc
}
trap cleanup EXIT INT TERM

# --- Passwort-Prüfung ------------------------------------------------------
# Written on demand into WORKDIR (which only exists after preflight).
write_password_verifier() {
    cat > "$WORKDIR/verify_password.py" <<'RADIX_VERIFY_EOF'
"""Check a password against this machine's shadow entry.

Exit 0 = matches, 1 = does not match, 2 = cannot tell.

crypt(3) through ctypes rather than Python's crypt module: that module was
removed in 3.13, and `openssl passwd` cannot do yescrypt ($y$), which is the
default on current Ubuntu and Debian. libcrypt implements exactly the schemes
the system itself uses, which is the guarantee we need here.

"Cannot tell" must never block the run — it only means we lose the early
warning, and a wrong password shows up as a failed setup that Radix reports.
"""
import ctypes
import ctypes.util
import os
import sys

SHADOW_FILE = os.environ.get("RADIX_SHADOW_FILE", "/etc/shadow")


def shadow_hash(user):
    try:
        with open(SHADOW_FILE, "r", encoding="utf-8") as fh:
            for line in fh:
                parts = line.split(":")
                if parts and parts[0] == user:
                    return parts[1] if len(parts) > 1 else ""
    except OSError:
        return None
    return None


def load_libcrypt():
    for candidate in (ctypes.util.find_library("crypt"),
                      "libcrypt.so.1", "libcrypt.so.2", "libcrypt.so"):
        if not candidate:
            continue
        try:
            return ctypes.CDLL(candidate)
        except OSError:
            continue
    return None


def verify(password, hashed):
    lib = load_libcrypt()
    if lib is None:
        try:
            import crypt  # removed in Python 3.13
        except ImportError:
            return None
        return crypt.crypt(password, hashed) == hashed
    lib.crypt.restype = ctypes.c_char_p
    lib.crypt.argtypes = [ctypes.c_char_p, ctypes.c_char_p]
    try:
        out = lib.crypt(password.encode(), hashed.encode())
    except (OSError, ValueError):
        return None
    if not out:
        return None
    return out == hashed.encode()


def main():
    hashed = shadow_hash(os.environ["RADIX_OS_USER"])
    if not hashed or not hashed.startswith("$"):
        return 2          # locked, empty, or no such entry
    result = verify(os.environ["RADIX_OS_PASSWORD"], hashed)
    if result is None:
        return 2
    return 0 if result else 1


if __name__ == "__main__":
    sys.exit(main())
RADIX_VERIFY_EOF
}

# Returns 0 = correct, 1 = wrong, 2 = undecidable.
check_password() {
    set +e
    RADIX_OS_USER="$OS_USER" RADIX_OS_PASSWORD="$1" \
        python3 "$WORKDIR/verify_password.py"
    local rc=$?
    set -e
    return $rc
}

gen_password() { python3 -c 'import secrets; print(secrets.token_urlsafe(18))'; }

# --- Begrüssung ------------------------------------------------------------

welcome() {
    cat <<'RADIX_LOGO_EOF'

     _      _____ __  __  ___     _     _   _
    | |    | ____|\ \/ /|_ _|   / \   | \ | |
    | |    |  _|   \  /  | |   / _ \  |  \| |
    | |___ | |___  /  \  | |  / ___ \ | |\  |
    |_____||_____|/_/\_\|___|/_/   \_\|_| \_|

RADIX_LOGO_EOF

    printf '%sBei LEXIAN registrieren%s\n\n' "$C_BOLD" "$C_RESET"
    cat <<EOF
Es freut uns, dass Sie sich für LEXIAN entschieden haben.

Damit die LEXIAN AG die Software auf dieser Maschine installieren, aktualisieren
und im Betrieb unterstützen kann, braucht es zwei Dinge:

  1. eine gesicherte Verbindung von dieser Maschine zu LEXIAN
  2. ein Benutzerkonto auf dieser Maschine, über das die Wartung läuft

Dieses Skript richtet beides ein und führt Sie Schritt für Schritt hindurch. Es
dauert wenige Minuten. Verändert wird nur, was Sie vorher bestätigt haben: die
Änderungen an dieser Maschine werden vorher zusammengefasst.

Voraussetzung: Sie haben den öffentlichen SSH-Schlüssel dieser Maschine im
LEXIAN Onboarding-Portal hinterlegt.

EOF
}

welcome
ask_yes_no "Wollen Sie mit der Konfiguration dieser Maschine jetzt starten?" j || abort

# ===========================================================================
# 1. Preflight
# ===========================================================================

step "Schritt 1 von 5: Voraussetzungen prüfen"
info "Wir prüfen, ob alles Nötige vorhanden ist und ob diese Maschine LEXIAN"
info "über das Internet erreicht. In diesem Schritt wird nichts verändert."
printf '\n'

[ "$(id -u)" -eq 0 ] || fail "Das Skript muss als root laufen:

        sudo bash install.sh"

for cmd in ssh ssh-keygen getent useradd usermod chpasswd; do
    command -v "$cmd" >/dev/null 2>&1 || fail "Das Programm '$cmd' fehlt auf diesem System."
done

ok "Systemwerkzeuge vorhanden"

# python3 is not a requirement this script invents. The automated setup that
# follows runs Ansible, and Ansible executes its modules by shipping Python to
# the managed node — jobs/setup-radix/main.yml uses template/systemd/stat/file,
# and nothing in the ansible repo bootstraps an interpreter via `raw`. So a box
# without python3 cannot be onboarded at all; it would just fail later with a
# far less obvious error.
#
# Ubuntu ships it on every install (Priority: important), but on Debian it is
# only Priority: optional, so it can genuinely be missing. This script is the
# one step that runs before Ansible and it already has root, which makes it
# the right place to close that gap instead of reporting it.
ensure_python3() {
    if command -v python3 >/dev/null 2>&1; then
        ok "python3 vorhanden"
        return 0
    fi

    info "Auf dieser Maschine fehlt python3."
    info "Es wird für die Einrichtung zwingend benötigt — sowohl von diesem"
    info "Skript als auch von der anschliessenden automatischen Installation."
    info ""
    ask_yes_no "python3 jetzt installieren?" j || abort

    # Package name is python3 everywhere except Arch, where it is python.
    # Every invocation gets stdin from /dev/null. Package managers happily read
    # the terminal (debconf, prompts), and doing so DRAINS input that was queued
    # for our own questions — an automated or here-doc-fed run then loses the
    # answers to everything after this point and hangs at the next prompt. Cost
    # a 900 s test timeout to find.
    if command -v apt-get >/dev/null 2>&1; then
        DEBIAN_FRONTEND=noninteractive apt-get -qq update </dev/null >/dev/null 2>&1 || true
        DEBIAN_FRONTEND=noninteractive apt-get -qq install -y python3 </dev/null >/dev/null 2>&1 || true
    elif command -v dnf >/dev/null 2>&1; then
        dnf install -y -q python3 </dev/null >/dev/null 2>&1 || true
    elif command -v yum >/dev/null 2>&1; then
        yum install -y -q python3 </dev/null >/dev/null 2>&1 || true
    elif command -v zypper >/dev/null 2>&1; then
        zypper --non-interactive --quiet install python3 </dev/null >/dev/null 2>&1 || true
    elif command -v pacman >/dev/null 2>&1; then
        pacman -Sy --noconfirm --quiet python </dev/null >/dev/null 2>&1 || true
    elif command -v apk >/dev/null 2>&1; then
        apk add --no-cache python3 </dev/null >/dev/null 2>&1 || true
    else
        fail "python3 fehlt und es wurde kein bekannter Paketmanager gefunden.
    Bitte python3 manuell installieren und das Skript erneut ausführen."
    fi

    command -v python3 >/dev/null 2>&1 || fail \
        "python3 konnte nicht installiert werden.
    Vermutlich hat dieser Server keinen Zugang zu den Paketquellen.
    Bitte python3 manuell installieren und das Skript erneut ausführen."

    PYTHON_INSTALLED=1
    ok "python3 installiert"
}

ensure_python3

acquire_lock

# Outbound reachability. /dev/tcp is a bash builtin, so this needs no extra
# tooling. A failure here is fatal on purpose: without this port nothing else
# in the script can work, and a clear message beats a confusing ssh error.
if timeout 8 bash -c "exec 3<>/dev/tcp/$RADIX_HOST/$RADIX_PORT" 2>/dev/null; then
    ok "Verbindung nach $RADIX_HOST:$RADIX_PORT möglich"
else
    fail "$RADIX_HOST:$RADIX_PORT ist nicht erreichbar.
    Die Firewall muss ausgehende Verbindungen auf Port $RADIX_PORT erlauben.
    Eingehend muss nichts geöffnet werden."
fi

WORKDIR="$(mktemp -d)"
chmod 700 "$WORKDIR"

# Unix socket paths are limited to ~108 bytes by the kernel, and ssh rejects
# an over-long -R spec outright. Check rather than fail cryptically later.
HANDOFF_SOCKET="$WORKDIR/handoff.sock"
if [ "${#HANDOFF_SOCKET}" -gt 100 ]; then
    fail "Der temporäre Pfad ist zu lang ($HANDOFF_SOCKET).
    Bitte TMPDIR auf ein kurzes Verzeichnis setzen, z.B. TMPDIR=/tmp."
fi

# ===========================================================================
# 2. Was soll eingerichtet werden? (nur Fragen, keine Änderungen)
# ===========================================================================
#
# Everything the run needs is decided here, before anything on the machine is
# touched: which account, which key, what has to be repaired. Then §4 shows one
# summary and asks once. A customer who answers "no" leaves behind a machine
# that was only read from, never written to — which is what makes it safe to
# just try the script and see what it wants to do.

step "Schritt 2 von 5: Benutzerkonto festlegen"
info "Über dieses Konto installiert und wartet LEXIAN die Software; es braucht"
info "deshalb sudo-Rechte. Existiert das Konto noch nicht, legen wir es an."
info ""
info "LEXIAN benötigt dazu das Passwort dieses Kontos. Ob wir eines vorschlagen"
info "oder Sie das bestehende eingeben, hängt davon ab, ob das Konto schon"
info "existiert — das klären wir gleich."
info ""
if [ "$INTERACTIVE" -eq 0 ]; then
    info "Kein Terminal erkannt — es werden die Standardwerte verwendet."
fi

# Who is running this? sudo tells us; otherwise fall back to the login name.
# Matters because of the password reset below: if the customer is logged in AS
# the maintenance account, the script would hand their own password to LEXIAN and
# they would not know it afterwards. Their running session survives — the sshd
# reload signals only the listener, never their connection — but the next login
# or sudo prompt would lock them out.
INVOKING_USER="${SUDO_USER:-}"
if [ -z "$INVOKING_USER" ] && command -v logname >/dev/null 2>&1; then
    INVOKING_USER="$(logname 2>/dev/null || true)"
fi

while :; do
    _candidate="$(ask_line "Benutzername" "$OS_USER")"

    if ! valid_username "$_candidate"; then
        if [ "$INTERACTIVE" -eq 0 ]; then
            fail "Ungültiger Benutzername: '$_candidate'"
        fi
        printf '    Ungültig. Erlaubt sind Kleinbuchstaben, Ziffern, "-" und "_";\n' > /dev/tty
        printf '    beginnend mit einem Buchstaben oder "_".\n' > /dev/tty
        continue
    fi

    if [ -n "$INVOKING_USER" ] && [ "$_candidate" = "$INVOKING_USER" ]; then
        printf '\n'
        warn "Sie sind gerade selbst als \"$_candidate\" angemeldet."
        info "Das Passwort dieses Kontos wird neu erzeugt und ausschliesslich an"
        info "LEXIAN übermittelt — Sie selbst kennen es danach nicht mehr. Diese"
        info "Sitzung bleibt bestehen, aber für eine neue Anmeldung oder für sudo"
        info "bräuchten Sie das Passwort."
        info "Empfehlung: ein eigenes Konto für die Wartung verwenden."
        printf '\n'
        if [ "$INTERACTIVE" -eq 0 ]; then
            warn "Unbeaufsichtigter Lauf — es wird mit '$_candidate' fortgesetzt."
        elif ! ask_yes_no "Trotzdem \"$_candidate\" verwenden?" n; then
            continue
        fi
    fi

    OS_USER="$_candidate"
    break
done
unset _candidate

write_password_verifier

# Does the account already exist? That decides everything about the password:
# a new account gets one suggested, an existing one keeps the password its owner
# already knows. Silently replacing the password of an account in use would take
# it away from the person who runs this script.
if getent passwd "$OS_USER" >/dev/null 2>&1; then
    PLAN_CREATE_USER=0
else
    PLAN_CREATE_USER=1
fi

OS_PASSWORD=""
#: new = suggested/typed for a fresh account · existing = the account's current
#: password, verified · reset = deliberately replaced · unverified = typed but
#: not checkable on this system.
PW_SOURCE=""

if [ "$PLAN_CREATE_USER" -eq 1 ]; then
    printf '\n'
    info "Das Konto \"$OS_USER\" gibt es noch nicht — wir legen es an."
    info "Wir haben ein sicheres Passwort vorgeschlagen. Sie können es"
    info "übernehmen oder ein eigenes eintragen."
    printf '\n'
    OS_PASSWORD="$(ask_line "Passwort" "$(gen_password)")"
    while [ -z "$OS_PASSWORD" ]; do
        [ "$INTERACTIVE" -eq 1 ] || fail "Kein Passwort angegeben."
        printf '    Das Passwort darf nicht leer sein.\n' > /dev/tty
        OS_PASSWORD="$(ask_line "Passwort" "$(gen_password)")"
    done
    PW_SOURCE="new"
elif [ "$INTERACTIVE" -eq 0 ]; then
    # Nobody to ask. Replacing the password unannounced would be the worst of
    # both worlds, so say plainly what is happening and why.
    printf '\n'
    warn "Das Konto \"$OS_USER\" existiert bereits, und es ist kein Terminal"
    warn "angeschlossen, an dem nach dem bestehenden Passwort gefragt werden"
    warn "könnte. Das Passwort wird deshalb NEU GESETZT und an LEXIAN"
    warn "übermittelt. Für einen Lauf, der das bestehende Passwort verwendet,"
    warn "das Skript in einem Terminal starten."
    OS_PASSWORD="$(gen_password)"
    PW_SOURCE="reset"
else
    printf '\n'
    info "Das Konto \"$OS_USER\" existiert bereits."
    info "Bitte geben Sie dessen Passwort ein, damit LEXIAN sich anmelden kann."
    info "Die Eingabe wird nicht angezeigt. Kennen Sie das Passwort nicht,"
    info "lassen Sie die Eingabe leer — dann setzen wir ein neues."
    printf '\n'

    _tries=0
    while [ -z "$PW_SOURCE" ]; do
        _tries=$((_tries + 1))
        _entered="$(ask_secret "Passwort von \"$OS_USER\"")"

        if [ -z "$_entered" ]; then
            if ask_yes_no "Neues Passwort erzeugen und für \"$OS_USER\" setzen?" j; then
                OS_PASSWORD="$(ask_line "Neues Passwort" "$(gen_password)")"
                [ -n "$OS_PASSWORD" ] || continue
                PW_SOURCE="reset"
            fi
            continue
        fi

        check_password "$_entered" && _rc=0 || _rc=$?
        case "$_rc" in
            0)
                OS_PASSWORD="$_entered"
                PW_SOURCE="existing"
                ok "Passwort geprüft"
                ;;
            1)
                printf '    Das Passwort ist nicht korrekt.\n' > /dev/tty
                if [ "$_tries" -ge 3 ]; then
                    printf '\n' > /dev/tty
                    if ask_yes_no "Stattdessen ein neues Passwort setzen?" j; then
                        OS_PASSWORD="$(ask_line "Neues Passwort" "$(gen_password)")"
                        [ -n "$OS_PASSWORD" ] && PW_SOURCE="reset"
                    else
                        abort
                    fi
                fi
                ;;
            *)
                warn "Das Passwort konnte auf diesem System nicht geprüft werden."
                warn "Es wird ungeprüft übernommen; stimmt es nicht, meldet LEXIAN"
                warn "das im Anschluss."
                OS_PASSWORD="$_entered"
                PW_SOURCE="unverified"
                ;;
        esac
    done
    unset _tries _entered _rc
fi

# ===========================================================================
# 3. SSH-Schlüssel finden
# ===========================================================================

step "Schritt 3 von 5: SSH-Schlüssel prüfen"
info "Mit einem SSH-Schlüssel weist sich diese Maschine gegenüber LEXIAN aus."
info "Es ist der Schlüssel, dessen öffentlichen Teil Sie im Onboarding-Portal"
info "hinterlegt haben."
printf '\n'

# Which of the keys on this machine is the registered one? The script does not
# decide that. It offers every candidate and lets LEXIAN's SSH server judge:
# only a key registered there authenticates. That keeps the check on the server,
# where this script — a file the customer can edit — cannot influence it.
#
# Four candidates at most on purpose: every offer counts against the server's
# MaxAuthTries (default 6), so a longer list would start failing connections for
# the wrong reason.
SSH_IDENTITY_ARGS=()
KEY_CANDIDATES=""
for candidate in \
    /root/.ssh/id_ed25519 /root/.ssh/id_rsa \
    "/home/$OS_USER/.ssh/id_ed25519" "/home/$OS_USER/.ssh/id_rsa"
do
    [ -f "$candidate" ] || continue
    SSH_IDENTITY_ARGS+=(-i "$candidate")
    KEY_CANDIDATES="$KEY_CANDIDATES $candidate"
done

if [ "${#SSH_IDENTITY_ARGS[@]}" -eq 0 ]; then
    fail "Auf dieser Maschine wurde kein SSH-Schlüssel gefunden.
    Gesucht wurde in /root/.ssh/ und /home/$OS_USER/.ssh/
    (id_ed25519 oder id_rsa).

    Ohne den Schlüssel, dessen öffentlichen Teil Sie im Onboarding-Portal
    hinterlegt haben, ist keine Verbindung zu LEXIAN möglich."
fi
ok "Gefundene Schlüssel:${KEY_CANDIDATES}"
info "Welcher davon gültig ist, entscheidet LEXIAN beim Verbinden."

# Host-Key des Zugangspunkts holen und gegen den mitgegebenen Fingerprint
# pruefen. Das IST das Pinning — nur dass der Schluessel geholt und verifiziert
# wird, statt im Skript mitzureisen. Deshalb kann dasselbe Skript fuer jeden
# Zugangspunkt gelten, auch fuer einen, den es beim Erstellen noch nicht gab.
#
# Erst danach wird known_hosts geschrieben; stimmt der Fingerprint nicht, endet
# der Lauf hier — bevor ein Konto existiert und lange bevor ein Passwort
# irgendwohin geht.
KNOWN_HOSTS="$WORKDIR/known_hosts"

_scanned="$(ssh-keyscan -T 10 -p "$RADIX_PORT" -t ed25519 "$RADIX_HOST" 2>/dev/null \
            | grep -v '^#' || true)"
[ -n "$_scanned" ] || fail \
    "Der Server $RADIX_HOST:$RADIX_PORT hat seinen Schlüssel nicht ausgeliefert.

    Erreichbar war er (siehe Schritt 1), er antwortet aber nicht wie ein
    SSH-Server. Bitte die Angabe hinter --host prüfen."

_seen_fp="$(printf '%s\n' "$_scanned" | ssh-keygen -lf - 2>/dev/null | awk '{ print $2 }')"
if [ "$_seen_fp" != "$HOST_KEY_FP" ]; then
    fail "Der Server $RADIX_HOST:$RADIX_PORT ist nicht der erwartete.

    Erwartet:  $HOST_KEY_FP
    Gefunden:  ${_seen_fp:-unlesbar}

    Damit wird abgebrochen, denn über diese Verbindung würden Zugangsdaten
    dieser Maschine übermittelt. Bitte den Befehl aus dem LEXIAN
    Onboarding-Portal unverändert verwenden und bei Zweifeln Lexian
    kontaktieren: $SUPPORT_CONTACT"
fi

printf '%s\n' "$_scanned" > "$KNOWN_HOSTS"
chmod 600 "$KNOWN_HOSTS"
unset _scanned _seen_fp
ok "Zugangspunkt: $RADIX_HOST:$RADIX_PORT (Fingerprint stimmt)"

# ===========================================================================
# 4. Plan aufstellen und bestätigen lassen
# ===========================================================================

# Debian/Ubuntu use 'sudo', RHEL/SUSE 'wheel'.
SUDO_GROUP=""
for group in sudo wheel; do
    if getent group "$group" >/dev/null 2>&1; then SUDO_GROUP="$group"; break; fi
done

PLAN_FIX_SHELL=0
PLAN_CREATE_HOME=0
PLAN_ADD_GROUP=0
PLAN_PW_AUTH=0
CURRENT_SHELL=""
HOME_DIR=""

if [ "$PLAN_CREATE_USER" -eq 0 ]; then
    CURRENT_SHELL="$(getent passwd "$OS_USER" | awk -F: '{ print $7 }')"
    case "$CURRENT_SHELL" in
        *nologin|*/false|"") PLAN_FIX_SHELL=1 ;;
    esac
    HOME_DIR="$(getent passwd "$OS_USER" | awk -F: '{ print $6 }')"
    if [ -n "$HOME_DIR" ] && [ ! -d "$HOME_DIR" ]; then
        PLAN_CREATE_HOME=1
    fi
    if [ -n "$SUDO_GROUP" ] &&
       ! id -nG "$OS_USER" 2>/dev/null | tr ' ' '\n' | grep -qx "$SUDO_GROUP"; then
        PLAN_ADD_GROUP=1
    fi
else
    [ -n "$SUDO_GROUP" ] && PLAN_ADD_GROUP=1
fi

# Is password authentication already permitted for this user? `sshd -T` prints
# the effective configuration, so we only touch sshd when we actually have to.
# -C needs user/host/addr because a config may Match on any of them.
password_auth_already_ok() {
    local sshd_bin
    sshd_bin="$(command -v sshd || true)"
    [ -n "$sshd_bin" ] || sshd_bin="/usr/sbin/sshd"
    [ -x "$sshd_bin" ] || return 1
    "$sshd_bin" -T -C "user=$OS_USER,host=localhost,addr=127.0.0.1" 2>/dev/null |
        grep -qi '^passwordauthentication yes'
}

if password_auth_already_ok; then
    PASSWORD_AUTH="true"
else
    PLAN_PW_AUTH=1
fi

step "Schritt 4 von 5: Zusammenfassung"
info "Das ist alles, was auf dieser Maschine verändert wird:"
printf '\n'

if [ "$PLAN_CREATE_USER" -eq 1 ]; then
    printf '    %-22s %s\n' "Benutzer" "$OS_USER (wird neu angelegt)"
else
    printf '    %-22s %s\n' "Benutzer" "$OS_USER (existiert bereits)"
fi
case "$PW_SOURCE" in
    new)        printf '    %-22s %s\n' "Passwort" "wird gesetzt, an LEXIAN übermittelt" ;;
    existing)   printf '    %-22s %s\n' "Passwort" "bestehendes wird verwendet (geprüft), unverändert" ;;
    unverified) printf '    %-22s %s\n' "Passwort" "eingegebenes wird verwendet (ungeprüft), unverändert" ;;
    reset)      printf '    %-22s %s\n' "Passwort" "wird NEU GESETZT, an LEXIAN übermittelt" ;;
esac
[ "$PLAN_ADD_GROUP" -eq 1 ] &&
    printf '    %-22s %s\n' "sudo-Gruppe" "$OS_USER wird zu '$SUDO_GROUP' hinzugefügt"
[ "$PLAN_FIX_SHELL" -eq 1 ] &&
    printf '    %-22s %s\n' "Anmelde-Shell" "wird auf /bin/bash gesetzt (jetzt: ${CURRENT_SHELL:-leer})"
[ "$PLAN_CREATE_HOME" -eq 1 ] &&
    printf '    %-22s %s\n' "Home-Verzeichnis" "$HOME_DIR wird angelegt"
if [ "$PLAN_PW_AUTH" -eq 1 ]; then
    printf '    %-22s %s\n' "SSH-Server" "Passwort-Anmeldung nur für '$OS_USER' freigeben"
else
    printf '    %-22s %s\n' "SSH-Server" "unverändert (Passwort-Anmeldung ist erlaubt)"
fi
printf '\n'

ask_yes_no "Sollen diese Änderungen jetzt vorgenommen werden?" j || abort

# ===========================================================================
# 5. Änderungen ausführen
# ===========================================================================

step "Schritt 5 von 5: Einrichten und mit LEXIAN verbinden"

if [ "$PLAN_CREATE_USER" -eq 1 ]; then
    useradd -m -s /bin/bash "$OS_USER"
    ok "Benutzer angelegt"
else
    ok "Benutzer existiert bereits"
    if [ "$PLAN_FIX_SHELL" -eq 1 ]; then
        usermod -s /bin/bash "$OS_USER"
        ok "Anmelde-Shell auf /bin/bash gesetzt (war: ${CURRENT_SHELL:-leer})"
    fi
    if [ "$PLAN_CREATE_HOME" -eq 1 ]; then
        mkdir -p "$HOME_DIR"
        chown "$OS_USER":"$OS_USER" "$HOME_DIR"
        chmod 700 "$HOME_DIR"
        ok "Fehlendes Home-Verzeichnis $HOME_DIR angelegt"
    fi
fi

if [ "$PLAN_ADD_GROUP" -eq 1 ]; then
    usermod -aG "$SUDO_GROUP" "$OS_USER"
    ok "Zur Gruppe '$SUDO_GROUP' hinzugefügt"
elif [ -n "$SUDO_GROUP" ]; then
    ok "Bereits in der Gruppe '$SUDO_GROUP'"
else
    warn "Keine sudo-Gruppe gefunden ('sudo' oder 'wheel')."
    warn "'$OS_USER' braucht sudo-Rechte, sonst schlägt die Einrichtung fehl."
fi

# Only write when the password is ours to write. For PW_SOURCE=existing the
# account keeps exactly what its owner knows — that is the whole point of asking.
# chpasswd also clears a locked ('!') field, which unlocks a disabled account.
case "$PW_SOURCE" in
    new)
        printf '%s:%s\n' "$OS_USER" "$OS_PASSWORD" | chpasswd
        ok "Passwort gesetzt"
        ;;
    reset)
        printf '%s:%s\n' "$OS_USER" "$OS_PASSWORD" | chpasswd
        ok "Passwort neu gesetzt"
        ;;
    *)
        ok "Bestehendes Passwort bleibt unverändert"
        ;;
esac

# --- Password login for the maintenance user -------------------------------
# Radix authenticates to this machine as the maintenance user with the password
# handed over below — that is how ansible/tasks.py uses the OS_USER credential.
# So sshd has to accept password authentication for that user, and on a modern
# cloud image it does not: Ubuntu's cloud images ship
# PasswordAuthentication no in /etc/ssh/sshd_config.d/. Without this step the
# handoff succeeds and setup-radix then fails at "Permission denied", which is a
# miserable error to debug from the Radix side.
#
# Scoped to one user via a Match block instead of enabling password auth
# globally: the customer's own hardening stays intact for every other account.
# `Match all` closes the block explicitly — sshd_config.d files are Included at
# the TOP of sshd_config, so an unterminated Match would swallow the rest of the
# main configuration.

# Finds the pid of the sshd LISTENER, or nothing.
#
# Deliberately not pgrep/pidof/ps: procps-ng is absent from minimal RHEL-family
# installations (a Rocky 9 base image has none of pgrep, pkill or ps), and the
# reload below used to be gated on `pgrep -x sshd`. On such a host the gate
# failed, the reload was skipped silently, the new configuration never took
# effect — and Radix could not log in, while this script reported success. The
# pid file first, then /proc, which every Linux has.
#
# Only the listener, never a per-connection child: the customer is quite
# possibly running this script over one of those ssh sessions, and HUPing it
# would drop them mid-installation. sshd re-reads its configuration when the
# listener is signalled, which is all we need.
sshd_listener_pid() {
    local f pid comm ppid
    for f in /run/sshd.pid /var/run/sshd.pid; do
        [ -r "$f" ] || continue
        pid="$(cat "$f" 2>/dev/null)"
        case "$pid" in
            ""|*[!0-9]*) ;;
            *) [ -d "/proc/$pid" ] && { printf '%s' "$pid"; return 0; } ;;
        esac
    done
    for comm in /proc/[0-9]*/comm; do
        [ -r "$comm" ] || continue
        [ "$(cat "$comm" 2>/dev/null)" = "sshd" ] || continue
        pid="${comm#/proc/}"
        pid="${pid%/comm}"
        # Field 4 of stat is the parent pid; the listener is reparented to init.
        ppid="$(awk '{ print $4 }' "/proc/$pid/stat" 2>/dev/null)"
        if [ "$ppid" = "1" ]; then
            printf '%s' "$pid"
            return 0
        fi
    done
    return 1
}

ensure_password_auth() {
    PASSWORD_AUTH="false"

    local sshd_bin
    sshd_bin="$(command -v sshd || true)"
    [ -n "$sshd_bin" ] || sshd_bin="/usr/sbin/sshd"
    if [ ! -x "$sshd_bin" ]; then
        warn "Kein SSH-Server (sshd) gefunden. Lexian kann sich später nicht"
        warn "anmelden — bitte openssh-server installieren."
        return 0
    fi

    local main="/etc/ssh/sshd_config"
    local dropin_dir="/etc/ssh/sshd_config.d"
    local block
    block="$(printf '%s\n' \
        "# Von LEXIAN install.sh verwaltet — nicht manuell ändern." \
        "# Erlaubt Passwort-Anmeldung ausschliesslich für den Wartungs-Benutzer." \
        "Match User $OS_USER" \
        "    PasswordAuthentication yes" \
        "Match all")"

    local target=""
    if [ -d "$dropin_dir" ] && grep -qiE "^[[:space:]]*Include[[:space:]]+${dropin_dir}/\*\.conf" "$main" 2>/dev/null; then
        # Name sorts last so it wins over the distro's own drop-ins; sshd uses
        # the FIRST value it obtains, and the files are read in glob order.
        target="$dropin_dir/99-lexian-maintenance.conf"
        printf '%s\n' "$block" > "$target"
        chmod 644 "$target"
    else
        # No drop-in mechanism: append to the main file, idempotently.
        target="$main"
        if ! grep -q "Von LEXIAN install.sh verwaltet" "$main" 2>/dev/null; then
            printf '\n%s\n' "$block" >> "$main"
        fi
    fi

    if ! "$sshd_bin" -t 2>/dev/null; then
        warn "Die SSH-Server-Konfiguration wurde nicht übernommen ($target)."
        warn "Bitte 'sshd -t' auf dem Server prüfen."
        return 0
    fi

    # Reload only if sshd is actually running; in that case a failure matters,
    # because the new setting would not be in effect.
    _listener="$(sshd_listener_pid || true)"
    if [ -n "$_listener" ]; then
        if command -v systemctl >/dev/null 2>&1 &&
           { systemctl reload ssh 2>/dev/null || systemctl reload sshd 2>/dev/null; }; then
            :
        elif command -v service >/dev/null 2>&1 &&
             { service ssh reload >/dev/null 2>&1 || service sshd reload >/dev/null 2>&1; }; then
            :
        elif kill -HUP "$_listener" 2>/dev/null; then
            :
        else
            warn "sshd konnte nicht neu geladen werden — die Passwort-Anmeldung"
            warn "für '$OS_USER' greift erst nach einem Neustart des SSH-Servers."
        fi
    fi
    unset _listener

    PASSWORD_AUTH="true"
    ok "Passwort-Anmeldung für '$OS_USER' freigegeben ($target)"
}

if [ "$PLAN_PW_AUTH" -eq 1 ]; then
    ensure_password_auth
else
    ok "Passwort-Anmeldung für '$OS_USER' ist bereits erlaubt"
fi

# sudo capability. Root can ask without knowing the password. Informational
# only: sudo-rs and unusual sudoers layouts print differently, and a false
# alarm here must not stop the run.
SUDO_OK="false"
if command -v sudo >/dev/null 2>&1; then
    if sudo -l -U "$OS_USER" 2>/dev/null | grep -qiE 'may run|\(ALL'; then
        SUDO_OK="true"
        ok "sudo-Rechte vorhanden"
    else
        warn "Für '$OS_USER' konnten keine sudo-Rechte festgestellt werden."
        warn "Die Einrichtung braucht sie — bitte prüfen, falls sie fehlschlägt."
    fi
else
    warn "'sudo' ist nicht installiert. Die Einrichtung braucht es."
fi

# ===========================================================================
# 4. Handoff listener
# ===========================================================================

info ""
info "Diese Maschine baut jetzt eine ausgehende Verbindung zu LEXIAN auf."
info "Es wird kein Port für Zugriffe von aussen geöffnet."

HOST_KEYS="$(cat /etc/ssh/ssh_host_*_key.pub 2>/dev/null || true)"

cat > "$WORKDIR/watch_status.py" <<'RADIX_WATCH_EOF'
"""Print LEXIAN's progress once the port has been handed over to sshd.

After the switch the handoff channel is gone, so LEXIAN appends its progress to
a file on this machine — over the very SSH access it was just given — and this
watches that file. Same contract as the handoff: one JSON object per line,
terminal states "done" (exit 0) and "failed" (exit 1).
"""
import json
import os
import sys
import time

PATH = os.environ["RADIX_STATUS_FILE"]
DEADLINE = time.monotonic() + float(os.environ.get("RADIX_DEADLINE_S", "5400"))
TERMINAL = {"done": 0, "failed": 1}

seen = 0
while True:
    if time.monotonic() > DEADLINE:
        print("    Zeitüberschreitung — LEXIAN hat sich nicht mehr gemeldet.", flush=True)
        sys.exit(1)
    try:
        with open(PATH, "r", encoding="utf-8", errors="replace") as fh:
            lines = fh.readlines()
    except OSError:
        lines = []
    for raw in lines[seen:]:
        seen += 1
        line = raw.strip()
        if not line:
            continue
        try:
            msg = json.loads(line)
        except ValueError:
            continue
        state = str(msg.get("state", ""))
        print("    {}".format(msg.get("message") or state), flush=True)
        if state in TERMINAL:
            sys.exit(TERMINAL[state])
    time.sleep(1)
RADIX_WATCH_EOF

# Where LEXIAN reports progress once it can log in. In the maintenance user's
# home, pre-created 0600 and owned by that user, so only that account and root
# can write it — nothing else local can forge a completion message. The path
# travels in the payload instead of being guessed by both sides.
ENROLL_HOME="$(getent passwd "$OS_USER" | awk -F: '{ print $6 }')"
[ -n "$ENROLL_HOME" ] || ENROLL_HOME="/home/$OS_USER"
STATUS_FILE="$ENROLL_HOME/.lexian-enroll.status"
: > "$STATUS_FILE"
chown "$OS_USER":"$OS_USER" "$STATUS_FILE"
chmod 600 "$STATUS_FILE"
[ -n "$HOST_KEYS" ] || warn "Keine SSH-Host-Schlüssel gefunden — Radix kann diesen Server nicht pinnen."

cat > "$WORKDIR/handoff.py" <<'RADIX_HANDOFF_EOF'
"""One-shot handoff server for the enrollment credentials.

Listens on a unix socket (mode 0600 inside a 0700 root-owned directory), so
the credentials are unreadable by other local users. Radix reaches it through
the reverse forward and is the only remote party that can.

Every accepted connection is served the same single-line JSON payload; Radix
may probe or retry. Progress lines coming back are printed verbatim for the
customer. Terminal states: "done" (exit 0), "failed" (exit 1).

Credentials arrive via environment variables on purpose — argv is visible to
every local process through /proc.
"""
import json
import os
import socket
import sys
import time

DEADLINE = time.monotonic() + float(os.environ.get("RADIX_DEADLINE_S", "5400"))

#: This program only carries PHASE 1 — the credentials up, and LEXIAN's
#: acknowledgement back. "received" is therefore terminal here: it is the cue for
#: the shell to hand the port over to sshd, after which progress arrives on the
#: status file instead. "done" is accepted too, in case LEXIAN reports completion
#: without a separate ack; "failed" ends the run.
TERMINAL = {"received": 0, "done": 0, "failed": 1}

#: Touched by the shell once it has finished printing its own banner. Radix can
#: connect within milliseconds of the tunnel coming up, i.e. while the shell is
#: still writing to the same terminal, and two concurrent writers produce
#: output like "setup complete" above "connection established". Holding the
#: first message until the marker appears makes the ordering deterministic
#: instead of timing-dependent.
READY_FILE = os.environ.get("RADIX_READY_FILE", "")


def payload():
    host_keys = [
        line.strip()
        for line in os.environ.get("RADIX_HOST_KEYS", "").splitlines()
        if line.strip()
    ]
    return {
        "v": 1,
        "os_user": os.environ["RADIX_OS_USER"],
        "password": os.environ["RADIX_OS_PASSWORD"],
        "sudo_ok": os.environ.get("RADIX_SUDO_OK") == "true",
        "password_auth": os.environ.get("RADIX_PASSWORD_AUTH") == "true",
        # Where to report progress once this port serves sshd instead of us.
        "status_file": os.environ["RADIX_STATUS_FILE"],
        "host_keys": host_keys,
        "hostname": socket.gethostname(),
        "os": os.environ.get("RADIX_OS_INFO", ""),
    }


def emit(message):
    # Capped wait: a missing marker must never deadlock the handoff itself.
    if READY_FILE:
        limit = time.monotonic() + 60.0
        while not os.path.exists(READY_FILE) and time.monotonic() < limit:
            time.sleep(0.1)
    print("    {}".format(message), flush=True)


def serve_one(conn, blob):
    conn.sendall(blob)
    # Read progress until Radix closes or reports a terminal state.
    with conn.makefile("rb") as stream:
        for raw in stream:
            line = raw.strip()
            if not line:
                continue
            try:
                msg = json.loads(line.decode("utf-8"))
            except (UnicodeDecodeError, ValueError):
                continue
            state = str(msg.get("state", ""))
            emit(msg.get("message") or state)
            if state in TERMINAL:
                return TERMINAL[state]
    return None


def main():
    path = os.environ["RADIX_SOCKET"]
    server = socket.socket(socket.AF_UNIX, socket.SOCK_STREAM)
    # Never inherit a stale socket from a killed run.
    try:
        os.unlink(path)
    except FileNotFoundError:
        pass
    server.bind(path)
    os.chmod(path, 0o600)
    server.listen(1)

    blob = (json.dumps(payload()) + "\n").encode("utf-8")

    while True:
        remaining = DEADLINE - time.monotonic()
        if remaining <= 0:
            emit("Zeitüberschreitung — Lexian hat sich nicht gemeldet.")
            return 1
        server.settimeout(min(remaining, 30.0))
        try:
            conn, _addr = server.accept()
        except socket.timeout:
            continue
        except OSError as exc:
            emit("Verbindungsfehler: {}".format(exc))
            return 1
        with conn:
            conn.settimeout(300.0)
            try:
                rc = serve_one(conn, blob)
            except (socket.timeout, OSError):
                rc = None
        if rc is not None:
            return rc
        # Connection dropped without a terminal state — keep waiting.


if __name__ == "__main__":
    sys.exit(main())
RADIX_HANDOFF_EOF

OS_INFO="$( (. /etc/os-release 2>/dev/null && printf '%s' "${PRETTY_NAME:-}") || true)"

# ===========================================================================
# 5. Verbindung aufbauen (Phase 1) und Zugangsdaten übergeben
# ===========================================================================
#
# ONE reserved port, two phases, one SSH connection:
#
#   phase 1   -R <port>:<unix socket>     the credentials go up
#   phase 2   -R <port>:127.0.0.1:22      LEXIAN runs the setup — and this is
#                                         the steady state afterwards
#
# Nothing on the server forces a reverse forward to point at sshd; that is
# exactly why both phases can share one port, and why enrollment needs no port
# of its own. The switch happens in place over the mux socket (-O cancel, then
# -O forward), so there is no reconnect and no window where the port is unbound.
#
# Verified against the real access host: cancel releases the listener at once,
# the re-point is accepted, and a mux-added forward is still checked against
# permitlisten — so this is not a way around it.
#
# ssh's own stderr is captured rather than shown: none of it is actionable for
# the customer, and the failure path below reports it in context.

CONTROL_SOCKET="$WORKDIR/cm.sock"

ssh -M -S "$CONTROL_SOCKET" -f -N \
    "${SSH_IDENTITY_ARGS[@]}" \
    -o IdentitiesOnly=yes \
    -o BatchMode=yes \
    -o StrictHostKeyChecking=yes \
    -o UserKnownHostsFile="$KNOWN_HOSTS" \
    -o ExitOnForwardFailure=yes \
    -o ServerAliveInterval=30 \
    -o ServerAliveCountMax=3 \
    -o ConnectTimeout=15 \
    -R "$ENROLL_PORT:$HANDOFF_SOCKET" \
    -p "$RADIX_PORT" \
    "$TUNNEL_USER@$RADIX_HOST" 2>"$WORKDIR/ssh.err" || fail \
    "Die Verbindung zu LEXIAN konnte nicht aufgebaut werden.

    Mögliche Ursachen:
      * keiner der gefundenen SSH-Schlüssel ist bei LEXIAN registriert
        (gesucht:${KEY_CANDIDATES})
      * die Portnummer $ENROLL_PORT gehört nicht zu dieser Maschine
      * eine Firewall blockiert ausgehende Verbindungen auf Port $RADIX_PORT

    Meldung des SSH-Clients:
$(sed 's/^/        /' "$WORKDIR/ssh.err" 2>/dev/null | tail -5)"

CONTROL_UP=1
ok "Verbindung steht — LEXIAN hat den Schlüssel akzeptiert"

step "Übergabe an LEXIAN"
info "Die Zugangsdaten werden jetzt über die gesicherte Verbindung übergeben."
printf '\n'

RADIX_OS_USER="$OS_USER" \
RADIX_OS_PASSWORD="$OS_PASSWORD" \
RADIX_SUDO_OK="$SUDO_OK" \
RADIX_PASSWORD_AUTH="$PASSWORD_AUTH" \
RADIX_HOST_KEYS="$HOST_KEYS" \
RADIX_OS_INFO="$OS_INFO" \
RADIX_SOCKET="$HANDOFF_SOCKET" \
RADIX_STATUS_FILE="$STATUS_FILE" \
RADIX_READY_FILE="$WORKDIR/ready" \
RADIX_DEADLINE_S="$HANDOFF_DEADLINE_S" \
    python3 "$WORKDIR/handoff.py" &
HANDOFF_PID=$!

for _ in $(seq 1 50); do
    [ -S "$HANDOFF_SOCKET" ] && break
    kill -0 "$HANDOFF_PID" 2>/dev/null || break
    sleep 0.1
done
[ -S "$HANDOFF_SOCKET" ] || fail "Der lokale Übergabe-Dienst konnte nicht gestartet werden."

: > "$WORKDIR/ready"

set +e
wait "$HANDOFF_PID"
HANDOFF_RC=$?
set -e
HANDOFF_PID=""

[ "$HANDOFF_RC" -eq 0 ] || fail "Die Übergabe der Zugangsdaten wurde nicht abgeschlossen."
ok "Zugangsdaten übergeben"

# ===========================================================================
# 6. Phase 2: denselben Port auf den SSH-Dienst dieser Maschine umlegen
# ===========================================================================

step "Einrichtung durch LEXIAN"

ssh -S "$CONTROL_SOCKET" -O cancel -R "$ENROLL_PORT:$HANDOFF_SOCKET" \
    "$RADIX_HOST" >/dev/null 2>>"$WORKDIR/ssh.err" \
    || fail "Der Übergabe-Kanal konnte nicht geschlossen werden."

ssh -S "$CONTROL_SOCKET" -O forward -R "$ENROLL_PORT:127.0.0.1:22" \
    "$RADIX_HOST" >/dev/null 2>>"$WORKDIR/ssh.err" \
    || fail "Der Wartungszugang konnte nicht geöffnet werden.

    Meldung des SSH-Clients:
$(sed 's/^/        /' "$WORKDIR/ssh.err" 2>/dev/null | tail -3)"

# The handoff socket has served its purpose; nothing must be able to reach it.
if [ -n "$HANDOFF_PID" ] && kill -0 "$HANDOFF_PID" 2>/dev/null; then
    kill "$HANDOFF_PID" 2>/dev/null || true
fi
rm -f "$HANDOFF_SOCKET"

ok "Wartungszugang offen"
info ""
info "LEXIAN richtet die Instanz jetzt ein. Das kann einige Minuten dauern."
info "Bitte lassen Sie dieses Fenster offen, bis die Einrichtung gemeldet wird."
info "Ein Abbruch mit Strg+C beendet die Verbindung; das Skript kann danach"
info "jederzeit erneut ausgeführt werden."
printf '\n'

set +e
RADIX_STATUS_FILE="$STATUS_FILE" RADIX_DEADLINE_S="$HANDOFF_DEADLINE_S" \
    python3 "$WORKDIR/watch_status.py"
SETUP_RC=$?
set -e

if [ "$SETUP_RC" -eq 0 ]; then
    printf '\n%s%s%s\n' "$C_GREEN" "========================================================================" "$C_RESET"
    printf '%s ✓ Diese Maschine ist bei LEXIAN registriert.%s\n' "$C_GREEN" "$C_RESET"
    printf '%s%s%s\n\n' "$C_GREEN" "========================================================================" "$C_RESET"
    printf '  Eingerichtet wurde:\n\n'
    printf '    - das Benutzerkonto "%s" mit sudo-Rechten\n' "$OS_USER"
    printf '    - die Passwort-Anmeldung für dieses Konto (und nur für dieses)\n'
    printf '    - die Wartungsverbindung zur LEXIAN AG\n\n'
    case "$PW_SOURCE" in
        existing|unverified)
            printf '  Das bestehende Passwort von "%s" blieb unverändert;\n' "$OS_USER"
            printf '  LEXIAN verwendet es für die Wartung.\n\n'
            ;;
        *)
            printf '  Das Passwort von "%s" wurde gesetzt und an LEXIAN übermittelt.\n\n' "$OS_USER"
            ;;
    esac
    printf '  Sie können dieses Fenster jetzt schliessen. Die Verbindung wird\n'
    printf '  dabei beendet — LEXIAN baut sie bei Bedarf selbständig wieder auf.\n\n'
    printf '  Fragen? %s\n' "$SUPPORT_CONTACT"
    exit 0
fi

fail "Die Einrichtung wurde nicht abgeschlossen."
